on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        id: eas_build
        run: |
          # Start the build
          eas build --platform android --non-interactive --profile createAndroidAPK --wait
          
          APK_URL=$(echo "$BUILD_OUTPUT" | grep -o 'https://expo.dev/[^ ]*')

          if [ -z "$APK_URL" ]; then
            echo "Failed to retrieve APK URL from build output."
            exit 1
          else
            echo "APK_URL=${APK_URL}" >> $GITHUB_ENV
          fi

      - name: Output APK URL
        run: echo "APK URL is: ${{ env.APK_URL }}"

      # - name: Download APK
      #   if: success()
      #   run: |
      #     curl -o navGo.apk "$APK_URL"

      # - name: Upload APK as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: navGo.apk
      #     path: navGo.apk