on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        id: eas_build
        run: |
          eas build --platform android --non-interactive
          echo "APK_URL=$(eas build:list --status completed --platform android --limit 1 --output json | jq -r '.[0].artifacts.buildUrl')" >> $GITHUB_ENV

      # - name: Download APK
      #   if: success()
      #   run: |
      #     curl -o navGo.apk "$APK_URL"

      # - name: Upload APK as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: navGo.apk
      #     path: navGo.apk